#!/bin/bash

CUR_PATH=$(dirname $0)

cd $CUR_PATH
#java -Xmx2048M -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=30303,server=y,suspend=n -jar bin/org.apache.sling.launchpad-7-standalone.jar

java -Xmx2048M -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=30303,server=y,suspend=n -jar bin/org.apache.sling.launchpad-8-SNAPSHOT.jar
